software-deployment-method:
  - conda
conda-prefix: /.snakemake/envs/smk_rnaseq
scheduler: greedy
rerun-trigger: mtime
printshellcmds: True
keep-incomplete: True
cores: 80
resources:
  mem_mb: 500000  # 500GB
default-resources:
  mem_mb: 5000  # 5GB
set-threads:
  salmon: 4
  salmon_index: 10
  featurecounts_transposable_elements: 4
  star: 10
  star_index: 10
  haplotypecaller: 10
  mutect2: 10
  vep: 10
  annovar: 10
  fastp_paired_end: 4
  fastp_single_end: 4
  fastqc: 4
set-resources:
  salmon:
    mem_mb: 20000 # 20GB
  star:
    mem_mb: 100000  # 100GB
  mark_duplicates:
    mem_mb: 50000  # 50GB
  split_n_cigar_reads:
    mem_mb: 50000  # 50GB
  base_recalibrator:
    mem_mb: 50000  # 50GB
  apply_bqsr:
    mem_mb: 50000  # 50GB
  haplotypecaller:
    mem_mb: 10000  # 10GB
  mutect2:
    mem_mb: 10000  # 10GB
  learn_read_orientation_model:
    mem_mb: 10000  # 10GB
  get_pileup_summaries:
    mem_mb: 10000  # 10GB
  get_pileup_summaries_dna:
    mem_mb: 10000  # 10GB
  calculate_contamination:
    mem_mb: 10000  # 10GB
  filter_mutect_calls:
    mem_mb: 10000  # 10GB
  snpeff:
    mem_mb: 20000  # 20GB
